name: 注册账号

on:
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.11'

jobs:
  register-account:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 检查API_KEY环境变量
        run: |
          if ([string]::IsNullOrEmpty("${{ secrets.API_KEY }}")) {
            Write-Error "错误: 未设置 API_KEY。请在仓库的 Settings -> Secrets and variables -> Actions 中添加名为 API_KEY 的 secret。"
            exit 1
          }

      - name: 设置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 运行注册脚本
        run: python registerAc.py
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: 上传CSV文件
        uses: actions/upload-artifact@v4
        with:
          name: registered-accounts
          path: "**/*.{csv,log}"
          retention-days: 7