name: 注册账号

on:
  workflow_dispatch:
    inputs:
      DOMAIN:
        description: '请输入域名'
        required: true
        type: string

env:
  PYTHON_VERSION: '3.11'
  PYTHONIOENCODING: 'utf-8'

jobs:
  register-account:
    runs-on: windows-latest
    timeout-minutes: 30  # 添加超时限制
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 检查API_KEY环境变量
        shell: pwsh
        run: |
          if (-not $env:API_KEY) {
            Write-Error "错误: 未设置 API_KEY。请在仓库的 Settings -> Secrets and variables -> Actions 中添加名为 API_KEY 的 secret。"
            exit 1
          }
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: 设置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 设置中文环境
        run: |
          $env:LANG = "zh_CN.UTF-8"
          $env:LC_ALL = "zh_CN.UTF-8"
          [System.Environment]::SetEnvironmentVariable('LANG', 'zh_CN.UTF-8', 'Process')
          [System.Environment]::SetEnvironmentVariable('LC_ALL', 'zh_CN.UTF-8', 'Process')

      - name: 运行注册脚本
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: python registerAc.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
          DOMAIN: ${{ inputs.DOMAIN }}
          LANG: zh_CN.UTF-8
          LC_ALL: zh_CN.UTF-8

      - name: 上传CSV文件
        uses: actions/upload-artifact@v4
        with:
          name: registered-accounts
          path: "**/*.{csv,log}"
          retention-days: 7